apiVersion: apps/v1
kind: Deployment
metadata:
  name: suma-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suma
  template:
    metadata:
      labels:
        app: suma
    spec:
      containers:
      - name: suma
        image: gcr.io/wired-name-463505-d6/suma
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: suma-service
spec:
  selector:
    app: suma
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
